name = "Cafein - Ralph"
color = "cyan"

[[panes]]
id = "p1"
split = "horizontal"
children = [
    "p2",
    "p3",
]

[[panes]]
id = "p2"
type = "terminal"
directory = "/Users/zain/Code/GitHub/vibefromcafe/cafein.id"
commands = ["./ralph.sh"]

[[panes]]
id = "p3"
type = "terminal"
directory = "/Users/zain/Code/GitHub/vibefromcafe/cafein.id"
commands = ["lazygit"]

[params]
