name = "Cafein - tmux"
color = "cyan"

[[panes]]
id = "p1"
type = "terminal"
is_focused = true
directory = "/Users/zain/Code/GitHub/vibefromcafe/cafein.id"
commands = [
"amux launch cafein",
"tmux attach -t cafein"
]

[params]
