name = "Obsidian"
color = "magenta"

[[panes]]
id = "p1"
type = "terminal"
is_focused = true
directory = "/Users/zain/Library/Mobile Documents/iCloud~md~obsidian/Documents/obsidian-notes"
commands = ["opencode"]

[params]
